# Generated by Django 4.2.4 on 2023-08-08 05:57

from django.db import migrations, models
import radioapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='topic',
            field=models.ForeignKey(default=radioapp.models.get_default_topic, on_delete=models.SET(radioapp.models.get_default_topic), to='radioapp.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='keyword',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
